config/routes.rb
Congolisanga::Application.routes.draw do
  get "home_pages/Home"

  get "home_pages/AboutUs"

  get "home_pages/News"

  get "home_pages/UpdateRDC"

  get "home_pages/LinksTo"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def Home
  end

  def AboutUs
  end

  def News
  end

  def UpdateRDC
  end

  def LinksTo
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/views/home_pages/AboutUs.html.erb
<h1>HomePages#AboutUs</h1>
<p>Find me in app/views/home_pages/AboutUs.html.erb</p>

app/views/home_pages/Home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the congolisanga</h1>

  
  

<%= link_to image_tag("Congo-Lisanga.bmp", alt: "congolisanga"), 'http://rubyonrails.org/' %>

app/views/home_pages/LinksTo.html.erb
<h1>HomePages#LinksTo</h1>
<p>Find me in app/views/home_pages/LinksTo.html.erb</p>

app/views/home_pages/News.html.erb
<h1>HomePages#News</h1>
<p>Find me in app/views/home_pages/News.html.erb</p>

app/views/home_pages/UpdateRDC.html.erb
<h1>HomePages#UpdateRDC</h1>
<p>Find me in app/views/home_pages/UpdateRDC.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Congolisanga</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "CongoLisanga", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "AboutUs",    aboutUs_path %></li>
              <li><%= link_to "News", news_path %></li>
              <li><%= link_to "UpdateRDC", updateRDC_path %></li>  
              <li><%= link_to "LinksTo", linksTo_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>